### ISSUE TITLE
Follow up on guidelines for Consent Form

### ISSUE THREAD

**Issue by sampling** [barnardos/consent-form-builder#227]
_As a researcher
I want to be presented with contextual help 
So that I understand what each step of consent form builder refers to_

# Description

Previous card regarding guides: https://trello.com/c/Mrkkr3ij/306-2-add-guidance-paragraph-to-each-section-of-consent-form-builder
We implemented the guides for researcher and topic pages. Remaining help paragraphs are pending review and approval from Olivia / BREC. 

# Acceptance criteria
- [x] Obtain the final version of guides for the most of pages
- [x] Create cards for implementing the guides on consent form

**Comment by joelcarr** [comment]
Can this be closed @Jesskyri?

**Comment by Jesskyri** [comment]
this can be closed, yes
