### ISSUE TITLE
Use Typography from Design System for consistency

### ISSUE THREAD

**Issue by ritapatel7** [barnardos/consent-form-builder#231]
_As a user
I want to see consistency in the font and line spacing used
to make content easier to read and understand_ 

# Acceptance criteria
- [ ] Update font family to match Design System
- [ ] Update so font scales matches Design System
- [ ] Update Line heights
- [ ] Check for any other Typography updates that need to be made
- [ ] Check the new Design System amends work with the final printed consent form

**Comment by tosbourn** [comment]
One of the things we should carefully consider is a regression we found some time ago with some print issues on the final preview.

* related ticket: https://trello.com/c/tF5zdsHM/316-05-day-information-sheet-prints-with-an-error-on-second-heading-consentf-orm-rather-than-consent-form
* related PR that fixed it the first time around: https://github.com/barnardos/consent-form-builder-rails/pull/222

Manual testing seemed the best way to verify this.

**Comment by joelcarr** [comment]
Due to new frontend architecture, we will be applying design system rules page by page in new issues.
