### ISSUE TITLE
Update colours through Consent form to align with Design System

### ISSUE THREAD

**Issue by ritapatel7** [barnardos/consent-form-builder#232]
_As a developer
I want to make sure colours align to Design System
so form/content is accessible to all users_ 

# Acceptance criteria
- [ ] Update submit buttons to match green button on Design System
- [ ] Make font large on buttons to meet Accessibility requirements as per Design System
- [ ] Make sure all background colours align to colours on Design system ie field background (grey and green) notes on green background, error field colours etc
- [ ] Check the new Design System amends work with the final printed consent form

**Comment by joelcarr** [comment]
Due to new frontend architecture, we will be applying design system rules page by page in new issues.
