### ISSUE TITLE
Check if main content width needs changing

### ISSUE THREAD

**Issue by ritapatel7** [barnardos/consent-form-builder#233]
_As a developer
I would like to know why we are using certain widths for main content
so layouts are flexible and consistent throughout other projects too_ 

# Acceptance criteria
- [ ] Chat with Richard and team on reasons for choosing main content width for this and other projects
- [ ] Update width for consent form if required

**Comment by ritapatel7** [comment]
Main content area size different to digi tran. Best to keep one size for main content across apps? Unless specific size required
digi trans main content is 736px plus 1rem padding
consent form 672px

**Comment by joelcarr** [comment]
Due to new frontend architecture, we will be applying design system rules page by page in new issues.
