### ISSUE TITLE
Add consistent spacing 

### ISSUE THREAD

**Issue by ritapatel7** [barnardos/consent-form-builder#235]
_As a developer
I want to make sure spacing aligns to Design System
So layout is consistent and content accessible on all devices_ 

# Acceptance criteria
- [ ] Check current spacing between elements
- [ ] Update spacing to align with Design System
- [ ] Check the new Design System amends work with the final printed consent form
- [ ] Check layout of the header

**Comment by joelcarr** [comment]
Due to new frontend architecture, we will be applying design system rules page by page in new issues.
