### ISSUE TITLE
Content changes on preview page

### ISSUE THREAD

**Issue by Jesskyri** [barnardos/consent-form-builder#237]
## Description
One of the users of the most recent usability testing iss a member of BREC (Ethical research team) and as well as being a valuable usability participant, she has industry knowledge and has suggested we implement the following text changes

## Acceptance Criteria

- [x] Move the ‘About taking part’ section of the information sheet to the top to be seen first by participants
- [x] On ‘Sharing information’ section information sheet remove ‘Where possible, the lead researcher will speak to you first and ask you what you want to do about the situation.’ and replace with ‘All our researchers have received safeguarding training and will follow Barnardo’s guidance to manage these situations appropriately’
- [x] On ‘Storing’ section of form with ‘anonymised as we process it’ radio button is selected remove ‘Barnardo’s will hold research data for 2 years after the closure of the project, after which it will be deleted’ and replace with 'Barnardo’s will hold research data for 2 years after we finish the project and we will then delete it’ to make it more active and human.
- [x] On Recording page, remove ‘written notes’ and replace with ‘researcher’s written notes’ so that we’re more clear that any work done by participants is ‘the work created by participants during in session’ and we have consistency across researchers

**Comment by ritapatel7** [comment]
This needs to be deployed manually so will go through this with @elaine hopefully next week Wednesday.

**Comment by jeddy3** [comment]
I've created a separate issue for the release: https://github.com/barnardos/consent-form-builder/issues/250

We can keep this issue closed as the acceptance criteria have been met.
