### ISSUE TITLE
[2 days] Investigate approaches to align with Design System

### ISSUE THREAD

**Issue by jeddy3** [barnardos/consent-form-builder#246]
The Design System (on other products) are built using a component paradigm. The separation of concerns is based on solving isolated problems, rather than based on technology. The CFB follows the latter approach. As such, Design System components will need to be translated into this other paradigm. This could be an error-prone and long-winded process that could produce undesirable code quality. This spike is to investigate alternatives e.g. https://evilmartians.com/chronicles/evil-front-part-1

**Comment by joelcarr** [comment]
#251 has been created to show the new frontend architecture we are looking to go forward with. @ritapatel7 and I have sat together to list through the components that will be built for the new architecture which is:

- Title
- HeadingOne
- HeadingTwo
- OrderedList
- UnorderedList
- Paragraph
- Lede
- Link
- Layout
- Header
- ResearchGuidance - (Pages-rules component on DS)
- CommandListNavigation (green bar)
- Command
- **ShareOverlay**
- **SingleLineTextControl**
- **AnyOfManyChoiceControl**
- **OneOfManyChoiceControl**
- **EnableStep (for optional steps)**
- Submit
- ErrorSummary
- **LivePreview**
- LivePreviewsContainer
- **PrintCommand**
- ParticipentConsentSwitch
- InputtedData (preview page highlight)
- WritingField
- ReleaseTag (footer)
- HotJar

The ones in bold are complex components. They might be complex by either there being some javascript involved, modifying a Ruby helper, or a change in architecture (the live preview component). A lot of these can be grouped up into one ticket (ie Title, Lede, Paragraph, and Link) with minimal effort.

When it comes to tickets we will also have to consider the following:

- Build each step
- Check print version
- Define frontend tests
- Build preview page with same components as the old react version

**Comment by joelcarr** [comment]
Here is some sudo code of how `new.html.erb` would look with the proposed architecture:

```erb
<%= c("Title", title: "Create tailored consent and information forms") %>
<%= c("Lede", text: '
  This tool will guide you through a series of questions. Your answers
  will help generate tailored information sheets and consent forms
  for your project(s).
') %>

<%= c("Form"), model: @research_session, do %>
  <%= c("SingleLineTextControl"), name: :name, text_options: { autofocus: true }  %>
  <%= c("Submit"), text: "Create new form" %>
<% end %>
```
