### ISSUE TITLE
Get Docker working within Barnardo's network

### ISSUE THREAD

**Issue by tosbourn** [barnardos/consent-form-builder#249]
_As a developer
I need Docker to work
so that I can get up and running with a project quickly_

We have Docker set up for this project, and when ran outside of our network is works as expected.

Inside of our network Docker fails to run, the errors reported shows that the processes running inside the virtual machine can't get out onto our network.

``` shell
?: pgp.mit.edu: Connection refused
gpgkeys: HTTP fetch error 7: couldn't connect: Connection refused
```

We need to set the proxy address (`http://macproxy.barnardos.org.uk:8080`) and ask Docker to use this. 

Docker for Mac does come with a proxy settings page but this does not appear to be being honoured. 

![image](https://user-images.githubusercontent.com/456902/38605312-d0e2cacc-3d6a-11e8-9211-f6a5c33eddd6.png)

We should investigate why this isn't being honoured.

One solution is to add the relevant environment variables to our `Dockerfile`

``` bash
ENV http_proxy http://macproxy.barnardos.org.uk:8080
ENV https_proxy http://macproxy.barnardos.org.uk:8080
ENV all_proxy http://macproxy.barnardos.org.uk:8080
```

This solution would work inside our network, but not outside our network. We should see if we can make this more flexible.

## Acceptance Criteria

- [ ] A developer can run `docker-compose up` from within our corporate network and get the application running
- [ ] A developer can run `docker-compose up` from outside our corporate network and get the application running
- [ ] A developer does not need to think about the network they are on or add any additional configurations to their local setup

**Comment by kittysquee** [comment]
@tosbourn can this issue be closed as we now have access to the dev network?

**Comment by tosbourn** [comment]
Yes, great spot.
