### ISSUE TITLE
Update 'The session is held on' label on 'Where and when page' 

### ISSUE THREAD

**Issue by ritapatel7** [barnardos/consent-form-builder#308]
The first single line input field on 'where and when' page is using a <fieldset> tag on old consent form and on new one we are using paragraph for 'Please enter the time and date of the session' and label for 'The session is held on (optional)', so the paragraph will not be read out on screen reader when user tabs through the form.
Could we look at making this as one label ie just 'Please enter the time and date of the session (optional)' and remove 'The session is held on (optional)' as it's not advised to use <fieldset> on one field

https://accessibility.blog.gov.uk/2016/07/22/using-the-fieldset-and-legend-elements/

**Comment by jeddy3** [comment]
Made redundant by https://github.com/barnardos/consent-form-builder/issues/313
