### ISSUE TITLE
[0.25 days] Workshop to prioritise work

### ISSUE THREAD

**Issue by olliewright** [barnardos/consent-form-builder#309]
The Consent Form Builder needs to be a shippable companion to The Design System, to act as an exemplar when brining future Design System partners on board.

A spike is needed to write-up the tickets required to make this happen. 

Once this Spike is completed by @jeddy3 @kelliewellingtons @ritapatel7 @joelcarr  these tickets need to be prioritised alongside the Consent Form Builder current tickets in 'to do' and 'backlog' so that the work to be delivered this sprint is clear.

The ambition is to have a shippable Consent Form Builder product before the end of this sprint, so that focus can be placed on starting to upgrade the FGM tool this sprint. Let's see what this Spike reveals!

**Comment by jeddy3** [comment]
Tickets created and ready for estimating by @ritapatel7 and @joelcarr

**Comment by jeddy3** [comment]
Work estimated and prioritised.
