### ISSUE TITLE
Remove the version number

### ISSUE THREAD

**Issue by jeddy3** [barnardos/consent-form-builder#311]
_As a user
I don't want to see the version number
So that I can focus on the filling in the form undistracted_

## Description

The version number is for developers, not users. It probably better as metadata e.g. `<meta name="version" ...>`

## Acceptance Criteria

- [ ] Move the version number to a more appropriate place

**Comment by tosbourn** [comment]
I'm not even sure it is valuable as meta information tbh, we don't use this on other projects and we can work out the version fine.

I think this was initially put in when lots of wording was being tested and multiple versions were floating about.
