### ISSUE TITLE
Improve labels and content

### ISSUE THREAD

**Issue by kelliewellingtons** [barnardos/consent-form-builder#313]
_AS a user,
I NEED information and form labels to be written in plain English,
SO that I can complete the process easily first-time unaided._

## Links and resources

Copy document:
https://docs.google.com/document/d/1g7ET6R6PlLQVHjgrP8dwM51vttOLnTgIQIkUm0aFsbA/edit?usp=sharing

## Acceptance Criteria

- [ ] Form labels and content to follow what is outlined in the linked document
- [ ] Works on target devices and browsers

**Comment by ritapatel7** [comment]
If the content of labels and information has been finalised and approved then will this will be quick and simple to change

**Comment by joelcarr** [comment]
We should work on tidying up the `en.yml` file as part of this ticket.
