### ISSUE TITLE
Order and size controls consistently

### ISSUE THREAD

**Issue by jeddy3** [barnardos/consent-form-builder#320]
_As a user
I want the controls ordered and sized consistently
So that I don't have to have to needlessly think_

## Description

- Steps should start with a mandatory field
- Options within OfManyControls should start with the most intrusive
- Controls should be appropriately sized for their expected content, whilst minimising jaggedness

## Links and resources

- Google Content Doc for order https://docs.google.com/document/d/1g7ET6R6PlLQVHjgrP8dwM51vttOLnTgIQIkUm0aFsbA/

## Acceptance Criteria

- [ ] Duration and Phone controls should be shortened
- [ ] Controls expecting a sentence (i.e. Location, Food and drink provided, Participants need to bring) should be longer
- [ ] Reorder controls as laid out in Content Doc

**Comment by ritapatel7** [comment]
Simple enough to change but may need discussions on sizes of each field and whether we stick to single input text or multiline text box

**Comment by jeddy3** [comment]
I've tweaked the acceptance criteria to make things clearer i.e. shorten two controls, lengthen three controls (sticking with SingleLineTextControls) and reorder the controls to match the doc.

**Comment by ritapatel7** [comment]
Order of labels are done via ticket #313
