### ISSUE TITLE
Extract product description and prerequisites into start page

### ISSUE THREAD

**Issue by jeddy3** [barnardos/consent-form-builder#322]
_As a user
I want to know what the product is for and what the prerequisites are
so I won't be blocked midway through the journey_

## Description

Relies on `StartLink` component in DS

## Links and resources

- Copy document:
https://docs.google.com/document/d/1g7ET6R6PlLQVHjgrP8dwM51vttOLnTgIQIkUm0aFsbA/edit?usp=sharing

## Acceptance Criteria

- [ ] Create start page

**Comment by ritapatel7** [comment]
I am assuming need discussions around this or approval on content and needs checking with Jess and other team members?

**Comment by jeddy3** [comment]
Jess has OKed the initial copy changes (as they communicate the same points). A final review can also happen during the PR review process.
