### ISSUE TITLE
Print stylesheet styles links as clickable

### ISSUE THREAD

**Issue by tosbourn** [barnardos/consent-form-builder#338]
When printing the final consent form, some elements that are clickable in the UI are printed with an underline.

It makes sense that they appear clickable on screen, as a user affordance. When printed the underline serves to make the text seem more important than it is.

<img width="425" alt="screen shot 2018-07-25 at 14 49 44" src="https://user-images.githubusercontent.com/456902/43205044-587b0c5e-901a-11e8-9bee-d4c94e2ca1fa.png">

## Acceptance Criteria

- [ ] No links in text in the final form should be printed with an underline or colour.

**Comment by rinkashimikito** [comment]
fix in https://github.com/barnardos/consent-form-builder/pull/339
